"""Black-box test harness for the Atlas server (src/server.py).

Typical usage:

    from harness import AtlasServer

    with AtlasServer() as srv:
        status, headers, body = srv.get("/api/tree")

Characteristics:
- Each AtlasServer creates a self-contained temporary directory (copy of src/,
  web/ and templates/ — the engine's document skeletons —, a test content/
  mind, an initialized git repo, dist/ generated by build.py) then launches
  src/server.py in a subprocess on an ephemeral port.
- Local mode by default (no KB_AUTH_ENABLED): no auth, bind 127.0.0.1.
- HTTP redirects are NOT followed (we characterize the 3xx responses as-is).
- HTTP error codes (4xx/5xx) are returned normally, never raised.

Mind prerequisites encoded here (server behaviors at boot):
- ROOT is derived from __file__ (src/server.py → parent.parent): server.py MUST
  live in <tmp>/src/ and the content in <tmp>/content/.
- The server does NOT run build.py at boot in local mode: the harness runs
  src/build.py itself to produce dist/index.html (otherwise GET / falls back to
  the listing of the content/ directory).
- content/notes/quick.md must be in GFM checkbox format, otherwise
  migrate_legacy_format() (run at boot) attempts a migration.
- The test mind's .gitignore ignores dist/ but NOT content/: the server
  commits content/ after each write (trigger_sync). DO NOT copy the engine
  repo's .gitignore (it ignores content/ entirely).
"""
from __future__ import annotations

import http.cookiejar
import json
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parent.parent  # /…/atlas
SRC_DIR = REPO_ROOT / "src"
WEB_DIR = REPO_ROOT / "web"
TEMPLATES_DIR = REPO_ROOT / "templates"

TODO_REL = "notes/quick.md"  # engine default (config.DEFAULT_TODO_FILE, [todo].file)

# Exact reproduction of the format written by write_todos() (TODO_HEADER + H2
# Travail/Personnel sections): a quick.md already in this format is stable at
# boot (migrate_legacy_format does not touch a file containing "- [ ]").
DEFAULT_QUICK_MD = (
    "# To-do\n\n"
    "Liste éditable depuis le widget en bas à droite du viewer.\n\n"
    "## Travail\n\n"
    "- [ ] Préparer le bilan mensuel\n"
    "- [x] Review the draft\n"
    "\n"
    "## Personnel\n\n"
    "- [ ] Tester le build PoE\n"
    "\n"
)

# Default mind: a few realistic docs with cross [[wikilinks]] (by path, by
# stem, with alias) and a subfolder. Tests can start from dict(DEFAULT_MIND)
# and add/overwrite entries.
DEFAULT_MIND: dict[str, str] = {
    "accueil.md": (
        "# Accueil\n\n"
        "Bienvenue dans le mind de test.\n\n"
        "Voir [[projets/alpha]] et [[beta|le projet Bêta]].\n"
    ),
    "projets/alpha.md": (
        "# Projet Alpha\n\n"
        "Document avec accents : déjà, café, hétérogène.\n\n"
        "Retour vers [[accueil]] et lien voisin [[projets/beta.md]].\n"
    ),
    "projets/beta.md": (
        "# Projet Bêta\n\n"
        "Aucun lien sortant ici. Cible de backlinks seulement.\n"
    ),
    TODO_REL: DEFAULT_QUICK_MD,
}

# dist/ and caches stay out of git (as in prod); content/ and .notes/ are
# versioned (the server commits them via trigger_sync). .atlas/ (the
# users/shares registry of ATLAS_STORE=file mode) must NEVER be committed: it
# contains password and token hashes.
TEST_GITIGNORE = "__pycache__/\n*.pyc\ndist/\n.atlas/\n"


def find_free_port() -> int:
    """Free port via ephemeral bind (port 0). A small race window is possible
    between the close and the server's bind — AtlasServer retries on
    collision (see start())."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


class Response(NamedTuple):
    """HTTP response: tuple (status, headers, body) + .text / .json() helpers."""
    status: int
    headers: "object"  # http.client.HTTPMessage (case-insensitive get())
    body: bytes

    @property
    def text(self) -> str:
        return self.body.decode("utf-8", "replace")

    def json(self):
        return json.loads(self.body)


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None  # 3xx surface as HTTPError → captured as-is


class AtlasServer:
    """Context manager: sets up a temporary mind and launches server.py on it.

    Parameters:
      mind        : dict {relative_path_under_content/: content}. None → copy of
                    DEFAULT_MIND. The quick.md expected by the todos is NOT
                    added automatically if a custom mind is passed (provide it
                    yourself if the test touches the todos).
      extra_env   : extra env variables for the server subprocess. The "{root}"
                    pattern in a value is replaced by the mind's tmpdir (unknown
                    before start()). E.g. cloud mode:
                    {"KB_AUTH_ENABLED": "1", "SESSION_SECRET": "…",
                     "KB_REPO_PATH": "{root}"} — short-circuits the git clone at
                    boot (ensure_repo_cloned() returns early if
                    <KB_REPO_PATH>/.git exists; requires git_init=True).
      cookies     : True → a CookieJar shared across requests (Set-Cookie
                    replayed automatically). Default False (stateless requests).
      run_build   : False → do not run build.py (characterize boot without
                    dist/index.html).
      git_init    : False → no git repo in the mind (characterize the
                    best-effort behavior of trigger_sync without git).
      extra_files : dict {relative_path_under_the_mind_ROOT: content},
                    written before build/boot — for files outside content/
                    (extensions .atlas/extensions/*, a test atlas.toml…).
      boot_timeout: max delay (s) for /healthz to respond.

    Attributes exposed after start(): root (tmp Path), content_root, dist_dir,
    port, base_url, proc (Popen), log_path (server stdout+stderr).
    """

    def __init__(self, *, mind: dict | None = None, extra_env: dict | None = None,
                 cookies: bool = False, run_build: bool = True,
                 git_init: bool = True, boot_timeout: float = 15.0,
                 extra_files: dict | None = None):
        self.mind = dict(DEFAULT_MIND) if mind is None else dict(mind)
        self.extra_env = dict(extra_env or {})
        self.extra_files = dict(extra_files or {})
        self.use_cookies = cookies
        self.run_build = run_build
        self.git_init = git_init
        self.boot_timeout = boot_timeout

        self.root: Path | None = None
        self.content_root: Path | None = None
        self.dist_dir: Path | None = None
        self.port: int | None = None
        self.base_url: str | None = None
        self.proc: subprocess.Popen | None = None
        self.log_path: Path | None = None
        self._log_file = None
        self._opener = None
        self.cookie_jar = http.cookiejar.CookieJar() if cookies else None

    # ── lifecycle ────────────────────────────────────────────────────────────

    def __enter__(self) -> "AtlasServer":
        self.start()
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.stop()

    def start(self) -> None:
        self.root = Path(tempfile.mkdtemp(prefix="atlas-test-"))
        self.content_root = self.root / "content"
        self.dist_dir = self.root / "dist"
        try:
            self._populate()
            if self.git_init:
                self._init_git()
            if self.run_build:
                self.build()
            self._launch_with_retries()
        except BaseException:
            self.stop()
            raise

    def stop(self) -> None:
        if self.proc is not None:
            if self.proc.poll() is None:
                self.proc.terminate()
                try:
                    self.proc.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    self.proc.kill()
                    self.proc.wait()
            self.proc = None
        if self._log_file is not None:
            self._log_file.close()
            self._log_file = None
        if self.root is not None and not os.environ.get("ATLAS_TEST_KEEP"):
            # ignore_errors: a git/build started by trigger_sync may still be
            # writing during the rmtree right after the kill.
            shutil.rmtree(self.root, ignore_errors=True)
            self.root = None

    # ── internal setup ───────────────────────────────────────────────────────

    def _populate(self) -> None:
        ignore = shutil.ignore_patterns("__pycache__", "*.pyc")
        shutil.copytree(SRC_DIR, self.root / "src", ignore=ignore)
        shutil.copytree(WEB_DIR, self.root / "web", ignore=ignore)
        if TEMPLATES_DIR.is_dir():
            shutil.copytree(TEMPLATES_DIR, self.root / "templates", ignore=ignore)
        (self.root / ".gitignore").write_text(TEST_GITIGNORE, encoding="utf-8")
        for rel, content in self.mind.items():
            target = self.content_root / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
        # Files at the mind root (outside content/): extensions
        # (.atlas/extensions/*), atlas.toml… present BEFORE build.py and the
        # server boot, which discover them at startup.
        for rel, content in self.extra_files.items():
            target = self.root / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")

    def _git_env(self) -> dict:
        env = os.environ.copy()
        # Isolate from the machine's git configs (gpgsign, global hooks, etc.).
        env["GIT_CONFIG_GLOBAL"] = os.devnull
        env["GIT_CONFIG_SYSTEM"] = os.devnull
        env["GIT_TERMINAL_PROMPT"] = "0"
        # An ambient ATLAS_MIND would redirect build.py and server.py to a mind
        # other than the test's tmpdir (tests that want a decoupled mind pass it
        # explicitly via extra_env).
        env.pop("ATLAS_MIND", None)
        return env

    def git(self, *args: str, check: bool = False) -> subprocess.CompletedProcess:
        """git in the test mind (machine config neutralized)."""
        return subprocess.run(
            ["git", *args], cwd=str(self.root), env=self._git_env(),
            capture_output=True, text=True, timeout=30, check=check,
        )

    def _init_git(self) -> None:
        self.git("init", "-q", "-b", "main", check=True)
        self.git("config", "user.email", "tests@atlas.local", check=True)
        self.git("config", "user.name", "Atlas Tests", check=True)
        self.git("add", "-A", check=True)
        self.git("commit", "-q", "-m", "test: initial mind", check=True)
        # No remote: trigger_sync's pushes fail best-effort, which is the
        # characterized behavior.

    def build(self) -> subprocess.CompletedProcess:
        """Runs the mind's src/build.py (generates dist/index.html + sidecars)."""
        result = subprocess.run(
            [sys.executable, str(self.root / "src" / "build.py")],
            cwd=str(self.root), env=self._git_env(),
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"build.py failed (exit {result.returncode}):\n"
                f"stdout: {result.stdout}\nstderr: {result.stderr}"
            )
        return result

    def _server_env(self, port: int) -> dict:
        env = self._git_env()
        # Purge any cloud residue from the calling environment.
        for var in ("KB_AUTH_ENABLED", "GITHUB_REPO_URL",
                    "KB_REPO_PATH", "SESSION_SECRET", "GITHUB_WEBHOOK_SECRET",
                    "GIT_PULL_INTERVAL", "ATLAS_STORE", "ATLAS_STORE_DIR",
                    "ATLAS_TRUSTED_IP_HEADER"):
            env.pop(var, None)
        env["PORT"] = str(port)
        env["PYTHONUNBUFFERED"] = "1"
        for key, value in self.extra_env.items():
            env[key] = value.replace("{root}", str(self.root))
        return env

    def _launch_with_retries(self, attempts: int = 3) -> None:
        last_error = ""
        for _ in range(attempts):
            self.port = find_free_port()
            self.base_url = f"http://127.0.0.1:{self.port}"
            self.log_path = self.root / "server.log"
            self._log_file = open(self.log_path, "ab")
            self.proc = subprocess.Popen(
                [sys.executable, str(self.root / "src" / "server.py")],
                cwd=str(self.root),
                env=self._server_env(self.port),
                stdout=self._log_file,
                stderr=subprocess.STDOUT,
            )
            if self._wait_ready():
                return
            # Early death: port collision → retry, otherwise propagate.
            self._log_file.close()
            self._log_file = None
            last_error = self.read_log()
            if "Address already in use" not in last_error:
                break
        raise RuntimeError(
            f"The server did not start on port {self.port}.\n"
            f"--- server.log ---\n{last_error[-4000:]}"
        )

    def _wait_ready(self) -> bool:
        deadline = time.monotonic() + self.boot_timeout
        while time.monotonic() < deadline:
            if self.proc.poll() is not None:
                return False  # process died before listening
            try:
                status, _, _ = self.get("/healthz", timeout=2)
                if status == 200:
                    return True
            except (urllib.error.URLError, ConnectionError, OSError):
                pass
            time.sleep(0.05)
        return False

    def read_log(self) -> str:
        """Current contents of server.log (server stdout+stderr)."""
        if self.log_path is None or not self.log_path.exists():
            return ""
        return self.log_path.read_text(encoding="utf-8", errors="replace")

    def path(self, rel: str) -> Path:
        """Absolute path of a mind doc (under content/)."""
        return self.content_root / rel

    # ── HTTP helpers ─────────────────────────────────────────────────────────

    def _get_opener(self):
        if self._opener is None:
            handlers = [_NoRedirect()]
            if self.cookie_jar is not None:
                handlers.append(urllib.request.HTTPCookieProcessor(self.cookie_jar))
            self._opener = urllib.request.build_opener(*handlers)
        return self._opener

    def request(self, method: str, path: str, *, data: bytes | None = None,
                json_body=None, headers: dict | None = None,
                timeout: float = 10.0) -> Response:
        """Raw HTTP request → Response(status, headers, body).

        - json_body: object serialized to JSON (Content-Type added if absent).
        - 3xx/4xx/5xx are returned, never raised.
        - No Accept-Encoding: the server responds un-gzipped (unless the test
          sends the header itself — it will then receive raw gzip).
        """
        hdrs = dict(headers or {})
        if json_body is not None:
            data = json.dumps(json_body, ensure_ascii=False).encode("utf-8")
            hdrs.setdefault("Content-Type", "application/json")
        req = urllib.request.Request(
            self.base_url + path, data=data, headers=hdrs, method=method.upper())
        try:
            with self._get_opener().open(req, timeout=timeout) as resp:
                return Response(resp.status, resp.headers, resp.read())
        except urllib.error.HTTPError as e:
            body = e.read()
            e.close()
            return Response(e.code, e.headers, body)

    def get(self, path: str, **kw) -> Response:
        return self.request("GET", path, **kw)

    def post(self, path: str, **kw) -> Response:
        return self.request("POST", path, **kw)

    def put(self, path: str, **kw) -> Response:
        return self.request("PUT", path, **kw)

    def patch(self, path: str, **kw) -> Response:
        return self.request("PATCH", path, **kw)

    def delete(self, path: str, **kw) -> Response:
        return self.request("DELETE", path, **kw)
