"""The HTTP request Handler: plumbing (cookies, sessions, CSRF, gzip, static serve)
plus the auth guard methods the router calls. Route bodies live in server/routes/*.py;
this class only carries the request machinery + guards + the do_<VERB> dispatchers.
Module-level helpers and config are reached through the `server` facade (`_s`)."""
from http.server import SimpleHTTPRequestHandler
import server as _s
from server.app import router, routes_table
import gzip
import html
import json
import os
import posixpath
import re
import sys


class Handler(SimpleHTTPRequestHandler):
    # Explicit MIME types for /vendor/: the system mimetypes table can miss
    # woff2 on some distros, and the browser then rejects mistyped fonts/CSS.
    extensions_map = {
        **SimpleHTTPRequestHandler.extensions_map,
        ".js": "text/javascript; charset=utf-8",
        ".css": "text/css; charset=utf-8",
        ".woff2": "font/woff2",
    }

    def __init__(self, *args, **kwargs):
        # Static handler serves content/ (.md); dist/ indices are intercepted
        # before it, PWA assets (web/) redirected by translate_path below.
        super().__init__(*args, directory=str(_s.CONFIG.content_root), **kwargs)

    def translate_path(self, path):
        clean = path.split("?", 1)[0].split("#", 1)[0]
        if clean == "/manifest.json":
            # PWA manifest is generated by build.py into dist/, not static in web/.
            return str(_s.CONFIG.dist_dir / "manifest.json")
        if clean in ("/icon.svg", "/favicon.ico", "/sw.js"):
            return str(_s.CONFIG.web_dir / clean.lstrip("/"))
        if clean.startswith("/vendor/"):
            # Open prefix → anti-traversal: after normpath a path escaping
            # /vendor/ (/vendor/../src/server.py) no longer starts with it → 404.
            from urllib.parse import unquote as _unquote
            normalized = posixpath.normpath(_unquote(clean))
            if normalized.startswith("/vendor/"):
                target = _s.CONFIG.web_dir / normalized.lstrip("/")
                if target.is_dir():
                    # Refuse directories: a trailing slash would otherwise render
                    # an HTML autoindex. Only FILES are served under /vendor/.
                    return str(_s.CONFIG.web_dir / "vendor" / "__refused__")
                return str(target)
            return str(_s.CONFIG.web_dir / "vendor" / "__refused__")
        return super().translate_path(path)

    def end_headers(self):
        # Security headers on ALL responses, centralized here. `no-referrer`
        # prevents a /share link token leaking via Referer to an external link
        # clicked from the doc. HSTS only in cloud (HTTPS).
        self.send_header("X-Content-Type-Options", "nosniff")
        # SAMEORIGIN (not DENY): the viewer renders .html docs in a same-origin
        # iframe (standalone deck/dashboard) which DENY would break; SAMEORIGIN
        # still blocks third-party clickjacking. Iframe stays sandbox=allow-scripts.
        self.send_header("X-Frame-Options", "SAMEORIGIN")
        self.send_header("Referrer-Policy", "no-referrer")
        if _s.CONFIG.auth_enabled:
            self.send_header("Strict-Transport-Security",
                             "max-age=63072000; includeSubDomains")
        super().end_headers()

    # ── auth ─────────────────────────────────────────────────────────────────

    def _session(self):
        """Returns {'email','role'} or None. In local mode, fakes an admin session."""
        if not _s.CONFIG.auth_enabled:
            return {"email": "local", "role": "admin"}
        cookie_header = self.headers.get("Cookie", "")
        for part in cookie_header.split(";"):
            part = part.strip()
            if part.startswith(_s.COOKIE_NAME + "="):
                return _s.verify_token(part[len(_s.COOKIE_NAME) + 1:])
        return None

    def _hidden_folders(self):
        """Folders (prefixes relative to content/) forbidden for the current
        viewer. Admin / local mode / no-auth → []. The 'api' role doesn't use
        cookie sessions, so it never reaches here."""
        sess = self._session()
        if not sess or sess.get("role") == "admin":
            return []
        user = _s.get_store().get_user_by_email(sess["email"])
        folders = (user or {}).get("hidden_folders") or []
        return [f.strip("/") for f in folders if isinstance(f, str) and f.strip("/")]

    def _viewer_ctx(self):
        """Per-request ACL context (model B). No session (local mode / no-auth) →
        superuser bypass (single operator on their own machine). A logged-in
        account (admin or viewer) → subject to the per-document ACL; the admin
        additionally curates the commons but does NOT see another user's private
        doc. The 'api' role never reaches here (no cookie session)."""
        sess = self._session()
        # Local mode (auth disabled) = single operator on their own machine →
        # superuser, regardless of the simulated admin session.
        if not _s.CONFIG.auth_enabled:
            return _s.ViewerCtx(set(), True, None, superuser=True)
        # Cloud + no session → anonymous, NOT superuser (fail closed). Content
        # routes are AUTH-guarded so this is defensive, but it must never grant a
        # full bypass to an unauthenticated caller.
        if not sess:
            return _s.viewer_ctx(None)
        return _s.viewer_ctx(sess)

    def _serve_index_filtered(self, rel):
        """Serve _backlinks.json / _notes-index.json with docs the current viewer
        can't read REMOVED (else the Mind/backlinks leak their names). Admin (no
        restriction) → fast static gzip path."""
        ctx = self._viewer_ctx()
        if ctx.superuser:
            self._serve_static_gzip(rel, "application/json; charset=utf-8")
            return
        try:
            data = json.loads((_s.CONFIG.dist_dir / rel).read_text(encoding="utf-8"))
        except (OSError, ValueError):
            self.send_error(404)
            return
        if isinstance(data, list):  # _tasks-index.json: [{path, line, text, done}]
            self._send_json(200, [
                it for it in data
                if isinstance(it, dict) and _s.can_read(it.get("path", ""), ctx)])
            return
        out = {}
        for path, val in data.items():
            if not _s.can_read(path, ctx):
                continue
            if isinstance(val, dict):  # _backlinks.json: {path: {in:[...], out:[...]}}
                val = {k: ([x for x in v if _s.can_read(x, ctx)]
                           if isinstance(v, list) else v)
                       for k, v in val.items()}
            out[path] = val
        self._send_json(200, out)

    def _is_authed(self):
        return self._session() is not None

    def _is_admin(self):
        sess = self._session()
        return sess is not None and sess.get("role") == "admin"

    def _require_auth_or_redirect(self):
        if self._is_authed():
            return True
        self.send_response(303)
        self.send_header("Location", "/login")
        self.end_headers()
        return False

    def _require_auth_or_401(self):
        if self._is_authed():
            return True
        self._send_json(401, {"error": "unauthorized"})
        return False

    def _require_admin_or_403(self):
        if not self._is_authed():
            self._send_json(401, {"error": "unauthorized"})
            return False
        if not self._is_admin():
            self._send_json(403, {"error": "forbidden"})
            return False
        return True

    def _request_origin_host(self):
        """Host of the request's origin (Origin, else Referer), or None if
        neither header is present. Used for the same-origin CSRF check."""
        from urllib.parse import urlsplit
        for header in ("Origin", "Referer"):
            value = self.headers.get(header)
            if value:
                # Origin "null" (sandbox/file://): no usable host → cross-origin.
                if value == "null":
                    return ""
                return urlsplit(value).netloc
        return None

    def _check_csrf_base_or_403(self):
        """Base CSRF defense (JSON Content-Type + same-origin). Defense-in-depth
        AND the only defense enforceable BEFORE a session exists (first-admin
        setup, otherwise protected by the constant-time setup-token). Local mode
        (auth disabled) stays open."""
        if not _s.CONFIG.auth_enabled:
            return True
        ctype = self.headers.get("Content-Type", "")
        content_length = int(self.headers.get("Content-Length") or 0)
        # Content-Type is only enforceable with a BODY: a bodyless mutating
        # request (DELETE /api/share/<id>, user delete) legitimately has none —
        # its CSRF defense then rests on same-origin + the X-CSRF-Token below.
        # Without this nuance every bodyless DELETE 415'd (share revoke broken).
        if content_length > 0 and "application/json" not in ctype.lower():
            self._send_json(415, {"error": "Content-Type must be application/json"})
            return False
        origin_host = self._request_origin_host()
        if origin_host is not None and origin_host != self.headers.get("Host", ""):
            self._send_json(403, {"error": "cross-origin request refused"})
            return False
        return True

    def _check_csrf_or_403(self):
        """Full CSRF defense for authenticated mutating requests, in order:
          1. application/json Content-Type required — a cross-site <form> can't
             emit it without a CORS preflight (blocked: no third-party origin).
          2. Same-origin Origin/Referer when present (else 403).
          3. Synchronizer X-CSRF-Token bound to the session, HMAC(secret,
             email|epoch): a third-party page can neither read the kb_csrf cookie
             (Same-Origin Policy) nor forge the HMAC. The strong barrier.

        Local mode (auth disabled) stays open: single-user on 127.0.0.1."""
        if not _s.CONFIG.auth_enabled:
            return True
        if not self._check_csrf_base_or_403():
            return False
        sess = self._session()
        if sess is None:
            self._send_json(401, {"error": "unauthorized"})
            return False
        epoch = _s.current_session_epoch(sess.get("email"))
        provided = self.headers.get("X-CSRF-Token", "")
        if not _s.verify_csrf_token(sess.get("email"), epoch, provided):
            self._send_json(403, {"error": "missing or invalid CSRF token"})
            return False
        return True

    def _require_api_bearer(self):
        """Verifies the Authorization: Bearer header + rate limit.

        Returns the user dict on success, or sends an error and returns None.
        Logs every successful call to stderr for audit.
        """
        sess = _s.verify_api_bearer(self.headers.get("Authorization", ""))
        if not sess:
            self._send_json(401, {"error": "invalid or missing bearer token"})
            return None
        auth = self.headers.get("Authorization", "")
        token = auth.strip().split(None, 1)[1] if " " in auth else ""
        if not _s.api_rate_limit_ok(_s._hash_api_token(token)):
            self._send_json(429, {"error": "rate limit exceeded (120/min)"})
            return None
        sys.stderr.write(f"[api] {self.command} {self.path} email={sess['email']}\n")
        sys.stderr.flush()
        return sess

    def _send_login_page(self, error=None, status=200):
        error_html = f'<p class="err">{html.escape(error)}</p>' if error else ""
        body = _s.render_page("login",
            error_html=error_html,
            site_name=html.escape(_s.CONFIG.site_name, quote=True),
            site_prefix=html.escape(_s.CONFIG.prefix, quote=True),
            lang=html.escape(_s.CONFIG.lang, quote=True),
            login_subtitle=html.escape(_s._t("login_subtitle"), quote=True),
            email_placeholder=html.escape(_s._t("login_email_placeholder"), quote=True),
            password_placeholder=html.escape(_s._t("login_password_placeholder"), quote=True),
            submit_label=_s._t("login_submit"),
            totp_subtitle=html.escape(_s._t("login_totp_subtitle"), quote=True),
            totp_intro=html.escape(_s._t("login_totp_intro")),
            totp_placeholder=html.escape(_s._t("login_totp_placeholder"), quote=True),
            totp_submit=_s._t("login_totp_submit"),
            totp_use_recovery=_s._t("login_totp_use_recovery"),
            totp_use_app=_s._t("login_totp_use_app"),
            recovery_intro=html.escape(_s._t("login_recovery_intro")),
            recovery_placeholder=html.escape(_s._t("login_recovery_placeholder"), quote=True),
            back_label=_s._t("login_back"),
            generic_error=html.escape(_s._t("login_generic_error"), quote=True),
        ).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _client_ip(self) -> str:
        """Real client IP behind a reverse proxy.

        If server.trusted_ip_header is configured, that header is authoritative
        — the LAST element if it carries a list: with an appending proxy (nginx
        `$proxy_add_x_forwarded_for`) only the last element is set by the trusted
        proxy; the left ones are client-supplied and forgeable (an attacker
        could rotate them to bypass the login rate limit)."""
        trusted_header = _s.CONFIG.trusted_ip_header
        if trusted_header:
            value = self.headers.get(trusted_header, "").split(",")[-1].strip()
            return value or self.client_address[0]
        # No trusted header: honor Fly-Client-IP only when actually on Fly
        # (platform-injected at the edge). We do NOT trust X-Forwarded-For here —
        # its leftmost element is client-forgeable. Self-hosters behind a proxy
        # must set server.trusted_ip_header.
        if os.environ.get("FLY_APP_NAME") or os.environ.get("FLY_ALLOC_ID"):
            fly_ip = self.headers.get("Fly-Client-IP", "").strip()
            if fly_ip:
                return fly_ip
        return self.client_address[0]

    def _session_cookie_pair(self, email: str, role: str, epoch: int):
        """The TWO Set-Cookie headers of an open session: the signed session
        cookie (HttpOnly) and the readable CSRF cookie (NOT HttpOnly, read by the
        page to set X-CSRF-Token). Same Max-Age, same Secure policy."""
        secure = "; Secure" if _s.CONFIG.auth_enabled else ""
        max_age = _s.CONFIG.session_max_age
        session_token = _s.make_token(email, role, epoch)
        csrf_token = _s.make_csrf_token(email, epoch)
        return [
            (f"{_s.COOKIE_NAME}={session_token}; Path=/; HttpOnly; "
             f"SameSite=Lax; Max-Age={max_age}{secure}"),
            # NOT HttpOnly on purpose: the page must read it to replay as a
            # header. Carries no secret (derived HMAC) and stealing it is not
            # enough — the HttpOnly session cookie is also required.
            (f"{_s.CSRF_COOKIE_NAME}={csrf_token}; Path=/; "
             f"SameSite=Lax; Max-Age={max_age}{secure}"),
        ]

    def _open_session_response(self, email: str, role: str):
        """303 to / with the session+CSRF cookies set (form login)."""
        epoch = _s.current_session_epoch(email)
        self.send_response(303)
        self.send_header("Location", "/")
        for cookie in self._session_cookie_pair(email, role, epoch):
            self.send_header("Set-Cookie", cookie)
        self.end_headers()

    def _verify_second_factor(self, user: dict, totp_code: str,
                              recovery_code: str) -> bool:
        """Validate the 2nd factor: TOTP code (constant time) OR single-use
        recovery code (consumed). The recovery code is only attempted if no TOTP
        code is provided, to avoid consuming a code by mistake."""
        if totp_code:
            step = _s.verify_totp_step(user.get("totp_secret") or "", totp_code)
            if step is None:
                return False
            # Anti-replay: refuse reusing a step already accepted (proxy-phishing
            # / shoulder-surf, a code is valid ~90s). Fail-open on a store hiccup
            # — never lock out a legitimate login over a hardening control.
            email = user.get("email") or ""
            if step <= _s.get_store().get_last_totp_step(email):
                return False
            _s.get_store().set_last_totp_step(email, step)
            return True
        if recovery_code:
            return _s.consume_recovery_code(user.get("email"), recovery_code)
        return False

    def _login_error(self, is_json: bool, message: str, status: int,
                     extra: dict = None):
        """Login error response: JSON for the SPA (with totp_required/locked
        flags), re-rendered HTML page for the form POST."""
        if is_json:
            payload = {"error": message}
            if extra:
                payload.update(extra)
            self._send_json(status, payload)
            return
        self._send_login_page(error=message, status=status)

    def _send_setup_page(self, error=None, status=200):
        error_html = f'<p class="err">{html.escape(error)}</p>' if error else ""
        body = _s.render_page("setup",
            error_html=error_html,
            site_name=html.escape(_s.CONFIG.site_name, quote=True),
            site_prefix=html.escape(_s.CONFIG.prefix, quote=True),
            lang=html.escape(_s.CONFIG.lang, quote=True),
            setup_subtitle=_s._t("setup_subtitle"),
            setup_intro=_s._t("setup_intro"),
            token_label=html.escape(_s._t("setup_token_label")),
            token_help=html.escape(_s._t("setup_token_help")),
            token_placeholder=html.escape(_s._t("setup_token_placeholder"), quote=True),
            email_label=html.escape(_s._t("setup_email_label")),
            email_placeholder=html.escape(_s._t("setup_email_placeholder"), quote=True),
            password_label=html.escape(_s._t("setup_password_label")),
            password_placeholder=html.escape(_s._t("setup_password_placeholder"), quote=True),
            submit_label=_s._t("setup_submit"),
        ).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Robots-Tag", "noindex, nofollow")
        self.end_headers()
        self.wfile.write(body)

    def _send_json_after_cookie(self, payload):
        """Sends a JSON body when the caller has already started the response
        (send_response + Set-Cookie set): we do NOT call send_response again,
        only the body headers + the body itself."""
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _send_share_error(self, reason: str):
        statuses = {"expired": 410, "revoked": 410, "invalid": 404,
                    "unavailable": 503}
        if reason not in statuses:
            reason = "invalid"
        body = _s.render_page("share-error",
            title=_s._t(f"share_{reason}_title"),
            message=_s._t(f"share_{reason}_message"),
            hint=_s._t(f"share_{reason}_hint"),
            site_name=html.escape(_s.CONFIG.site_name, quote=True),
            lang=html.escape(_s.CONFIG.lang, quote=True),
        ).encode("utf-8")
        status = statuses[reason]
        self.send_response(status)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Robots-Tag", "noindex, nofollow")
        self.end_headers()
        self.wfile.write(body)

    def _serve_share(self, token):
        path, error = _s.verify_share_token(token)
        if error:
            self._send_share_error(error)
            return
        target = (_s.CONFIG.content_root / path).resolve()
        try:
            target.relative_to(_s.CONFIG.content_root)
        except ValueError:
            self._send_share_error("invalid")
            return
        if not target.exists() or target.suffix.lower() not in (".md", ".html"):
            self._send_share_error("invalid")
            return
        # A shared .html is already a standalone page: served as-is (noindex),
        # no marked re-rendering — the owner's work, like a shared .md.
        if target.suffix.lower() == ".html":
            body = target.read_bytes()
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.send_header("X-Robots-Tag", "noindex, nofollow")
            self.end_headers()
            self.wfile.write(body)
            return
        # Strip leading YAML frontmatter before embedding, like the viewer build:
        # left in, marked renders the `tags:` line + closing `---` as a setext H2
        # that leaks into the page and the table of contents.
        _, content = _s._import_build()._parse_frontmatter(
            target.read_text(encoding="utf-8"))
        title = target.name
        extensions_css, extensions_js = _s.share_extension_assets()
        body = _s.render_page("share",
            title=html.escape(title),
            # `</` → `<\/`: a doc containing "</script>" must not close the
            # <script> tag and inject HTML outside the sanitized content.
            content_json=json.dumps(content).replace("</", "<\\/"),
            # Extension assets so extension-generated content keeps its design
            # and interactions once shared.
            extensions_css=extensions_css,
            extensions_js=extensions_js,
            lang=html.escape(_s.CONFIG.lang, quote=True),
            footer_label=_s._t("share_footer").format(
                site_name=html.escape(_s.CONFIG.site_name, quote=True)),
            toc_title=_s._t("share_toc_title"),
        ).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Robots-Tag", "noindex, nofollow")
        self.end_headers()
        self.wfile.write(body)

    def _bump_session_epoch(self, email: str) -> int:
        """Increments the account's session epoch → invalidates ALL issued
        cookies (the user's own AND any thief's). The read-increment-write isn't
        strictly atomic, but the monotonic increment suffices: two concurrent
        bumps invalidate the old sessions either way."""
        new_epoch = _s.current_session_epoch(email) + 1
        _s.get_store().upsert_user(email, {"session_epoch": new_epoch})
        return new_epoch

    # ── JSON helpers ─────────────────────────────────────────────────────────

    def _read_body(self) -> bytes:
        """Reads the request body, bounded to MAX_BODY_BYTES. Beyond the bound:
        return b"" and close the connection to discard the unread body (avoids
        memory blow-up). Callers treat b"" as an empty/invalid body."""
        length = _s._safe_int(self.headers.get("content-length"))
        if length > _s.MAX_BODY_BYTES:
            self.close_connection = True
            return b""
        return self.rfile.read(length) if length > 0 else b""

    def _read_json(self):
        body = self._read_body()
        if not body:
            return {}
        try:
            return json.loads(body)
        except (ValueError, json.JSONDecodeError):
            return {}

    def _accepts_gzip(self):
        return "gzip" in self.headers.get("Accept-Encoding", "").lower()

    def _send_bytes(self, status, body, content_type, extra_headers=None):
        """Sends bytes with gzip compression if the client supports it and body > 1KB."""
        headers = list(extra_headers or [])
        if self._accepts_gzip() and len(body) > 1024:
            body = gzip.compress(body, compresslevel=6)
            headers.append(("Content-Encoding", "gzip"))
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        for k, v in headers:
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(body)

    def _send_json(self, status, payload):
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self._send_bytes(status, body, "application/json; charset=utf-8",
                         [("Cache-Control", "no-store")])

    def _serve_static_gzip(self, rel, content_type):
        """Serves a static dist/ file with gzip + ETag revalidation (304).

        SimpleHTTPRequestHandler doesn't compress; for the large prose JSON
        indices we go through _send_bytes (gzip >1KB). The ETag (mtime-size) lets
        the browser revalidate and get a 304 when nothing changed."""
        target = (_s.CONFIG.dist_dir / rel).resolve()
        try:
            target.relative_to(_s.CONFIG.dist_dir)
        except ValueError:
            self.send_error(404)
            return
        if not target.is_file():
            self.send_error(404)
            return
        st = target.stat()
        etag = f'"{int(st.st_mtime)}-{st.st_size}"'
        if self.headers.get("If-None-Match") == etag:
            self.send_response(304)
            self.send_header("ETag", etag)
            self.end_headers()
            return
        body = target.read_bytes()
        self._send_bytes(200, body, content_type,
                         [("ETag", etag), ("Cache-Control", "no-cache")])

    def _todo_index_from_path(self):
        m = re.match(r"^/api/todos/(\d+)$", self.path)
        return int(m.group(1)) if m else None

    # ── extensions ───────────────────────────────────────────────────────────

    def _dispatch_extension(self):
        """Route the request to a server extension, first matching route wins.
        Returns True if one handled it (response already sent, including 401/403
        from the role guard), else False (caller falls through). A raising
        handler doesn't kill the thread: generic 500 + stderr log."""
        path = self.path.split("?", 1)[0]
        for method, regex, handler, role in _s._CTX.extension_routes:
            if method != self.command:
                continue
            match = regex.match(path)
            if not match:
                continue
            if role == "admin" and not self._require_admin_or_403():
                return True
            if role == "auth" and not self._require_auth_or_401():
                return True
            try:
                handler(self, match)
            except Exception as e:
                print(f"[extensions] erreur handler {self.command} {path}: {e}",
                      file=sys.stderr)
                try:
                    self._send_json(500, {"error": "extension error"})
                except Exception:
                    pass  # response already partially sent by the handler
            return True
        return False

    # ── verbs ────────────────────────────────────────────────────────────────

    def do_HEAD(self):
        # No HEAD pipeline: the parent's default serves file metadata straight from
        # disk, bypassing the route tables, the session guard and the per-document
        # ACL (an existence oracle on private docs). The viewer never uses HEAD.
        self.send_error(405)

    def do_GET(self):
        if router.dispatch(self, routes_table.GET_ROUTES):
            return
        # Extension routes BEFORE the session guard — role applied per route.
        if self._dispatch_extension():
            return
        # First-boot (cloud, no admin): navigable pages redirect to /setup until
        # the initial admin exists. Placed after the explicit API/Bearer/MCP/share
        # routes so it doesn't hijack those independent auth channels or /api/me.
        if _s.setup_is_open():
            self.send_response(303)
            self.send_header("Location", "/setup")
            self.end_headers()
            return
        if not self._require_auth_or_redirect():
            return
        self._serve_navigable()

    def _serve_navigable(self):
        """Static / navigable tail of do_GET (after the explicit routes,
        extension dispatch, setup redirect and session guard): dotfile/source
        ACL, hidden-folder ACL, gzip dist indices, .html intercept, then the
        stdlib static handler."""
        rel = self.path.split("?", 1)[0].lstrip("/")
        # Security: the static handler serves any file under ROOT, dotfiles
        # included. Refuse dotfiles (.git/config holds the GitHub PAT) and source
        # code (*.py/*.pyc). Checks MUST run on the CANONICAL path (normalized +
        # URL-decoded exactly as translate_path resolves it): otherwise a
        # non-normalized path (/a//b, %2f tricks) slips past the literal-prefix
        # ACL here while translate_path still serves the file — a real ACL bypass.
        from urllib.parse import unquote as _unquote
        _norm = posixpath.normpath(_unquote(self.path.split("?", 1)[0]))
        _decoded = "/".join(w for w in _norm.split("/") if w and w not in (".", ".."))
        if (any(p.startswith(".") for p in _decoded.split("/"))
                or _decoded.endswith((".py", ".pyc"))):
            self.send_error(404)
            return
        # Per-document ACL (model B): a doc the viewer can't read is "not found"
        # (no-existence-oracle). The same posixpath-normalized form is checked, so
        # %2f / double-slash tricks can't slip a private doc past the gate.
        _vctx = self._viewer_ctx()
        if not _vctx.superuser and not _s.can_read(_decoded, _vctx):
            self.send_error(404)
            return
        # _backlinks.json: served gzip + ETag 304 (static handler doesn't compress).
        if rel == "_backlinks.json":
            self._serve_index_filtered(rel)
            return
        # _notes-index.json (dist/): counters for the tree's badges. Without this
        # route the static handler (content/) 404'd and the viewer fell back to {}.
        if rel == "_notes-index.json":
            self._serve_index_filtered(rel)
            return
        # _tasks-index.json — computed LIVE from current files (not the dist
        # snapshot) so ticking a checkbox reflects immediately. Filtered per-viewer.
        if rel == "_tasks-index.json":
            tasks = _s._live_tasks_index()
            ctx = self._viewer_ctx()
            if not ctx.superuser:
                tasks = [t for t in tasks if _s.can_read(t.get("path", ""), ctx)]
            self._send_json(200, tasks)
            return
        if not rel or rel.endswith("/"):
            rel = (rel + "index.html") if rel else "index.html"
        if rel.endswith(".html"):
            target = (_s.CONFIG.dist_dir / rel).resolve()
            try:
                target.relative_to(_s.CONFIG.dist_dir)
                if target.is_file():
                    body = target.read_bytes()
                    # no-store: the shell inlines the app JS, so a cached shell = stale
                    # JS; it must be revalidated every load for a deploy to land.
                    self._send_bytes(200, body, "text/html; charset=utf-8",
                                     [("Cache-Control", "no-store")])
                    return
            except (ValueError, OSError):
                pass
        return super().do_GET()

    def do_POST(self):
        if router.dispatch(self, routes_table.POST_ROUTES):
            return
        # Extension routes (POST): after native routes, before the 404. Role per
        # route, default "admin".
        if self._dispatch_extension():
            return
        self.send_response(404)
        self.end_headers()

    def do_PATCH(self):
        # Per-route guards (like do_POST): notes + share repoint keep ADMIN_CSRF,
        # todos is CSRF_BASE (a member patches its OWN list). No blanket admin.
        if router.dispatch(self, routes_table.PATCH_ROUTES):
            return
        self.send_response(404)
        self.end_headers()

    def do_DELETE(self):
        # Per-route guards (like do_POST): admin routes carry ADMIN_CSRF, content
        # routes their own Guard (/api/file is CSRF_BASE → authorized per-document
        # in docs.delete). No blanket admin, so a member can delete a doc they own.
        if router.dispatch(self, routes_table.DELETE_ROUTES):
            return
        self.send_response(404)
        self.end_headers()

    def do_PUT(self):
        # Per-route guards (like do_POST): /api/file is CSRF_BASE → authorized
        # per-document in docs.file_put (create/edit ladder). No blanket admin.
        if router.dispatch(self, routes_table.PUT_ROUTES):
            return
        self.send_response(404)
        self.end_headers()

    def log_message(self, fmt, *args):
        if _s.CONFIG.auth_enabled:
            # Mask the MCP token in the path (/mcp/<token>) so it is not written
            # in clear text in the Fly logs.
            msg = re.sub(r"/mcp/[^/\s\"?]+", "/mcp/***", fmt % args)
            sys.stderr.write("%s - %s\n" % (self.address_string(), msg))
            sys.stderr.flush()
